### ISSUE TITLE
Add armeria-dropwizard

### ISSUE THREAD

**Issue by OneCricketeer** [dropwizard/modules.dropwizard.io#105]
Made this

https://github.com/line/armeria/pull/2236

Would like to see it listed as a module

**Comment by joschi** [comment]
@cricket007 Thanks for creating this issue!

Feel free to create a pull request to add your module to [`_data/modules/thirdparty.yaml`](https://github.com/dropwizard/modules.dropwizard.io/blob/2cbfb259fb1efd155ad63013d5c1cc93f0104568/_data/modules/thirdparty.yaml). 👍
