### ISSUE TITLE
Why using master and gh-pages branch?

### ISSUE THREAD

**Issue by ahus1** [dropwizard/modules.dropwizard.io#21]
Looking at the PR #20 I wonder if I should have submitted the pull request for the gh-pages branch in the first place. 

Thinking again: Why has this repo a master AND and gh-pages branch, why not a gh-pages branch only? 

Some more information about making the gh-pages branch the default branch are available here http://www.xanthir.com/b4Zz0 and here http://oli.jp/2011/github-pages-workflow/

**Comment by arteam** [comment]
It makes sense, since we have only static content in this repository.

@dropwizard/committers Does anyone have any objections for this?

**Comment by nickbabcock** [comment]
No objections, I think it is a good idea

**Comment by jplock** [comment]
Sounds good to me.

**Comment by arteam** [comment]
I've just realized that I don't have permissions to change the default branch in the repository.
I think only owners can do that. We will need help from @joschi, @carlo-rtr, or @ryankennedy.

**Comment by joschi** [comment]
I've made `gh-pages` the default branch and deleted the `master` branch.
