### ISSUE TITLE
How best to express version bounds?

### ISSUE THREAD

**Issue by jklukas** [dropwizard/modules.dropwizard.io#49]
I've noticed that there are several modules listed here that are compatible with newer versions of Dropwizard than the list indicates.

For example, I'm using https://github.com/tkrille/dropwizard-template-config with Dropwizard 1.0, but the page here lists "0.7, 0.8" for the version. When I first discovered this page, I skipped over the dropwizard-template-config project because I thought it wouldn't be compatible with newer DW versions.

Would it be okay for projects to list compatibility as something like "0.7+" to indicate there are no known issues with newer versions? Or is the expectation that package maintainers will periodically submit PRs here to update that their packages are compatible with newer dropwizard versions?

**Comment by joschi** [comment]
@jklukas Thanks for bringing this up.

There is no "official" way for expressing the version bounds of one of the listed 3rd party modules.

I guess listing the supported versions is fine ("0.8, 0.9, 1.0").

The reason I dislike open-ended version specifications ("0.7+") is that people would expect things to work with the latest stable version of Dropwizard even if the author(s) didn't test the compatibility.

**Comment by jklukas** [comment]
I might take a stab at a PR that adds some explicit instruction around this, in particular calling out that package maintainers will need to test on the new versions and update the listing here as new versions are released.

I would imagine we'd want to organize the packages based on most recent verified version. So a bundle that runs on 0.8, 0.9, and 1.0 would be listed with the 1.0 packages.

**Comment by ahus1** [comment]
@joschi / @jklukas - It seems that can now be closed as the PR is merged?

**Comment by jklukas** [comment]
Indeed. Closing.
